### ISSUE TITLE
Outlook untitled attachment

### ISSUE THREAD

**Issue by vladimirsbudkins** [eoghanobrien/php-simple-mail#17]
If message is with attachments, an open it in outlook. I have attachments, and untitled attachment ***.txt

**Comment by ndt** [comment]
This is because of a malformed MIME boundary. Closing boundary must end with 2 more hyphens. (see RFC 2046, 5.1.1, p.19)

> The boundary delimiter line following the last body part is a
   distinguished delimiter that indicates that no further body parts
   will follow.  Such a delimiter line is identical to the previous
   delimiter lines, with the addition of two more hyphens after the
   boundary parameter value.
>
>     --gc0pJq0M:08jU534c0p--

**Comment by eoghanobrien** [comment]
@vladimirsbudkins Thanks for reporting!

@ndt Thanks for fixing!
