### ISSUE TITLE
Send mail after form validation.

### ISSUE THREAD

**Issue by RealHoloDuck** [eoghanobrien/php-simple-mail#29]
Hi, I need help. I want send a mail with php-simple-mail. After form validation I get the setTo mail, but what is the correct setFrom mail?
Is a mail server required? Can it test it locally?

**Comment by eoghanobrien** [comment]
Hi @RealHoloDuck 

Your issue is not with the php-simple-mail code, it's with your email set up.

php-simple-mail uses the PHP [`mail()`](http://php.net/manual/en/function.mail.php) function.

The mail program (typically `sendmail`) to be used is defined by the configuration settings in the php.ini file. The mail function will work locally if you have configured PHP correctly to send mail.

If you don't know how to configure PHP, contact your hosting provider.

For more information, see https://www.w3schools.com/php/php_ref_mail.asp

**Comment by RealHoloDuck** [comment]
Thanks.
